version: '3'

silent: true

tasks:

  clean:
    desc: Clean built artefacts
    cmds:
      - cmd: rm -rf .vitepress/cache
      - cmd: rm -rf .vitepress/dist
      - cmd: rm -rf .deployment/app

  serve:
    desc: Start the server locally
    cmds:
      - task: clean
      - cmd: npm run docs:dev

  build:
    desc: Build the documentation
    cmds:
      - task: clean
      - cmd: npm run docs:build

  preview:
    desc: Preview the documentation
    cmds:
      - task: build
      - cmd: npm run docs:preview
